version: '3.8'

services:
  app:
    build: .
    image: php:8.2-fpm-custom
    container_name: breeze_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - mysql
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: breeze_web
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: breeze_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: breeze_composer
    volumes:
      - .:/app
    working_dir: /app
    command: ["composer", "install"]
    networks:
      - laravel

  node:
    image: node:18
    container_name: breeze_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    command: tail -f /dev/null  # 追加部分
    
volumes:
  dbdata:

networks:
  laravel: